---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: test_instance
    image: ubuntu:22.04
    pre_build_image: true

provisioner:
  name: ansible
  options:
    vvv: true
  inventory:
    links:
      group_vars: /home/tkhapchaev/devops/lab4/inventories/test/group_vars

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
